import express from 'express';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import healthRoutes from './routes/healthRoutes.js';
import { errorHandler, notFound } from './middleware/errorMiddleware.js';
const app = express();
app.use(cors({ origin: process.env.CLIENT_URL, credentials: true }));
app.use(express.json({ limit: '1mb' }));
app.use(cookieParser());
app.use('/api/health', healthRoutes);
app.use(notFound);
app.use(errorHandler);
export default app;
